ENV['COCOAPODS_DISABLE_STATS'] = "true"

platform :ios, '11.0'

use_frameworks!

target 'SimpleService' do
    pod 'Alamofire'
    pod 'BrightFutures'
end

target 'SimpleServiceTests' do
    pod 'AutoEquatable'
    pod 'BrightFutures'
    pod 'Quick'
    pod 'Nimble'
    pod 'KIF'
    pod 'KIF-Quick'
    pod 'Spry'
    pod 'Spry+Nimble'
end

